# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

#setup_for_device_change do |device, udid, language|
#    puts "Adding food photo to #{device}"
#    system("xcrun simctl boot #{udid}")
#    system("xcrun simctl addphoto #{udid} FruitImages/001-apple.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/016-pear.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/015-peach.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/012-lemon.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/023-strawberry.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/009-grapes.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/017-pineapple.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/003-banana.png")
#    system("xcrun simctl addphoto #{udid} FruitImages/005-cherry.png")
#end

platform :ios do
  desc "Generate new localized screenshots"

  lane :screenshots do
    capture_screenshots
    frame_screenshots
  end
  
  lane :test do
    ENV["FASTLANE_XCODE_LIST_TIMEOUT"] = "120" 
    scan
  end
  
  lane :multi_scan_test do
    multi_scan(
        # project: File.absolute_path('../AtomicBoy/AtomicBoy.xcodeproj'),
        scheme: 'PECS Maker',
        #try_count: 3, # retry _failing_ tests up to three times^1.
        fail_build: false,
        #parallel_testrun_count: 4, # run subsets of your tests on parallel simulators^2
        devices: ["iPhone 8 (14.5)", "iPhone 8 Plus (15.5)", "iPhone 14 Pro", "iPad Pro (12.9-inch) (6th generation)" ],
        clean: false,
        skip_build: true,
        number_of_retries: 3,
        max_concurrent_simulators: 4,
        #result_bundle: true,
        output_directory: "multi_scan_output/"
    )
    end
end
